version: '3.9'

services:
  nginx:
    image: "nginx:stable-alpine"
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./src:/var/www/laravel
  php:
    build: 
      context: docker/php
      dockerfile: php.Dockerfile
    container_name: laravel_base
    volumes:
      - ./src:/var/www/laravel:rw
      - ./docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini:ro
      - ./docker/php/conf.d/error_reporting.ini:/usr/local/etc/php/conf.d/error_reporting.ini:ro
    # command: sh -c "chmod -R 755 /var/www/laravel/storage"
    # chmod -R 777 /var/www/laravel/storage
    # environment:
      # XDEBUG_MODE: debug
      # XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003
    expose:
      - 9003
      # - 9000
      # - 9001
      # - 9002
    

  mysql:
    image: mysql:8
    container_name: laravel_mysql
    ports:
      - 3306:3306
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=laravel_db
      - MYSQL_USER=laravel
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password

  redis:
    image: redis:alpine
    container_name: laravel_redis
    ports:
      - 6379:6379

 

